# Generated by Django 6.0.2 on 2026-05-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('LOP', 'Loss of Pay (LOP)'), ('Casual Leave', 'Casual Leave'), ('Weekoff', 'Weekoff')], max_length=100),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
