# Generated by Django 6.0.2 on 2026-03-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField()),
                ('employee_id', models.CharField()),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_role', models.CharField(max_length=150)),
                ('employee_salary', models.FloatField()),
                ('employee_dob', models.DateField()),
                ('employee_address', models.CharField(max_length=500)),
                ('employee_phone_number', models.CharField(max_length=10)),
            ],
        ),
    ]
